---
AllCops:
  Include:
    - Rakefile
    - rakelib/**/*
  Exclude:
    - build/**/*
    - vendor/**/*
AbcSize:
  Max: 18
ClassLength:
  Max: 200
CyclomaticComplexity:
  Max: 10
Documentation:
  Enabled: false
EmptyLinesAroundModuleBody:
  Enabled: false
EmptyLinesAroundClassBody:
  Enabled: false
MultilineOperationIndentation:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 25
ParameterLists:
  Max: 6
PerceivedComplexity:
  Max: 10
